name: Deploy to Vercel
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup pnpm
        run: pnpm setup

      - name: Add pnpm to PATH
        run: echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          pnpm install -g vercel
          vercel --prod --token=$VERCEL_TOKEN